### ISSUE TITLE
Cannot delete a second project/group due to broken confirmation modal

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#636]
On the My Projects page, if a user deletes a project and then tries to delete a second project, or they cancel out of the first delete operation, they will be greeted by a broken delete modal upon their next attempt.

![image](https://user-images.githubusercontent.com/322346/119242852-4e2a4600-bb16-11eb-8f31-e501afddae84.png)

**Comment by schaferyan** [comment]
I encountered this while working on #514. Marking the `confirmDeleteProject` method in `MyProjectsController` as `async` seems to resolve the issue. If you want to add me to this issue I can submit a pull request for it, otherwise the fix can be included when I submit a PR for #514 (which will likely take some time) if that works.

**Comment by PeterBreen** [comment]
If you've got a solution for this, then by all means please submit a PR. I assigned you to the task just now, as you probably saw.
