### ISSUE TITLE
New blog posts are failing to load on Home page

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#983]
When new articles from our Ghost blog get loaded on the Home page, the page crashes with the following error:
`vendors.bundle.js:1 TypeError: Cannot read properties of null (reading 'name')`

While it's not clear why new ghost blog posts are missing a 'name', we clearly need to handle the case where no name is present (and locate alternate name fields if available).

**Comment by SleeplessRegina** [comment]
Just wondering how to reproduce this error? Is it in the blog column on Home page when I click the "Read More" link? 
<img width="1073" alt="Screen Shot 2023-06-28 at 14 06 31" src="https://github.com/DemocracyLab/CivicTechExchange/assets/71072255/fdd4cde8-ce39-4741-8494-95a01b47f502">

**Comment by LukasLimalkl** [comment]
I'm cant reproduce this error too. Can u give more infos?

**Comment by PeterBreen** [comment]
I don't see any blog posts causing trouble -- probably they were removed? Without that I think this issue is stuck. 

In case further information comes up here's some context:

both tags and authors have name fields:
https://github.com/DemocracyLab/CivicTechExchange/blob/a8c502990edd880f90f2122938fd889899c71365/common/components/componentsBySection/Landing/LatestBlogPosts.jsx#L46
https://github.com/DemocracyLab/CivicTechExchange/blob/a8c502990edd880f90f2122938fd889899c71365/common/components/componentsBySection/Landing/LatestBlogPosts.jsx#L61-L66

None of them have conditionals -- but without some API data from the blog to look at when it's failing, I can't say if this is the correct area to focus on for a fix.
